### ISSUE TITLE
Add  "Optional Chaining" (now implemented in Chrome)

### ISSUE THREAD

**Issue by dhb33** [chriszarate/bookmarkleter#25]
With your [https://chriszarate.github.io/bookmarkleter/](), I always have to put Off all my `?.` in original codes before I find where to put them back in the result.  Else, I'm getting an`unknown: Support for the experimental syntax 'optionalChaining' isn't currently enabled`and No result because of this error.

I use your Bookmarkleter  - a bit customized through Tampermonkey - to help me build our HTML page of Chrome bookmarklets. It is Really The Best Bookmarklet Maker I found!

**Comment by dhb33** [comment]
The error Im getting also ends with `Add @babel/plugin-proposal-optional-chaining (https://git.io/vb4Sk) to the 'plugins' section of your Babel config to enable transformation`. Thanks!

**Comment by chriszarate** [comment]
Fixed
