### ISSUE TITLE
Great update, but now DEFAULT minifying no longer happens

### ISSUE THREAD

**Issue by DarrenSem** [chriszarate/bookmarkleter#28]
Thanks so much for the updates! I confirmed things like foo?.bar or foo??bar now work.
Except it seems tonnow be broken; the DEFAULT minifying no longer happens (AKA if you uncheck all boxes, where you want to minify but not run Babel transform to convert to older code)

![Bookmarkleter update 02Mar2023 BUT breaks default](https://user-images.githubusercontent.com/106487066/222748543-cf51086e-aa67-4251-a7be-8d1bdac3f26a.jpg)

_Originally posted by @DarrenSem in https://github.com/chriszarate/bookmarkleter/issues/27#issuecomment-1453629832_

**Comment by DarrenSem** [comment]
...unless it was previously BROKEN (aka the default was simply to add prefix "javascript:" and not even remove line breaks? If so, I apologize for creating this new issue in error 😳

Much appreciated for you doing the update! How can I send you some $ in thanks

**Comment by chriszarate** [comment]
> unless it was previously BROKEN (aka the default was simply to add prefix "javascript:" and not even remove line breaks?

It was broken in a different way. It always minified via Babel Minify regardless of the state of that checkbox. There was no default minify, just Babel Minify.

Now the checkbox works (and is still checked by default). But unchecking probably doesn't make sense very often.

No need for $, just glad its useful. :)

**Comment by chriszarate** [comment]
I think the ideal solution is to separation minification and variable mangling. Minification can probably always be enabled. Variable mangling is an option.

**Comment by DarrenSem** [comment]
It appears in the previous version the checkbox for minifying was not working (aka it always minified whether or not selected).
Looks like you corrected that bug with this new update -- you made that toggle actually work, AND defaulted to it being selected. Perfect!

PS: please Tag a release 1.1.0 like you did for previous (2019 = 1.0.1) thanks for everything!

**Comment by DarrenSem** [comment]
Issue was created in error, because I did not realize the purpose of the "minify" checkbox was to allow you to DISABLE minifying (although, thankfully, you default to it being enabled).
