### ISSUE TITLE
Awesome project - thank you

### ISSUE THREAD

**Issue by rmacklin** [chriszarate/bookmarkleter#32]
No issue here - just wanted to say thanks for building this!

I've recently found myself wanting to create more bookmarklets for various tasks, and this makes it a breeze.

**Comment by SalmonWellDunn** [comment]
hello good people of earth!
![WIN_20231102_22_49_27_Pro](https://github.com/chriszarate/bookmarkleter/assets/156636020/9b6808aa-1ea0-43c7-8341-7a6d022c02e0)
