### ISSUE TITLE
500KB JavaScript, WOW!

### ISSUE THREAD

**Issue by JavaScript-Packer** [chriszarate/bookmarkleter#5]
https://github.com/JavaScript-Packer/24KB-Uglify.js is a link to my highly modded/fixed, minified and compressed version of Uglify that is only 24KB, maybe you can help me spread it's use... This could help you remake your marklet app in less than 30KB versus 475KB it is now.

It is the heart of www.scriptcompress.com and so far gets better results than most other minifiers. Use Google Closure compiler first and this fuglify will still make it smaller!

It's easy to use, max settings are set already and just one function to call:
```javascript
var code = 'alert("Your Code");';
var minified = fugly(code);

**Comment by JavaScript-Packer** [comment]
https://github.com/JavaScript-Packer/bookmarklet-maker/blob/master/bookmarkleter.htm is your app compressed (for client side decompressing) that is less than 150KB. Demo on http://codepen.io/samples/full/VLOVdG/

**Comment by chriszarate** [comment]
Nice work! I'll take a look.
